name: giobba
version: 0.1.0
queues: ["default", "background"]
workersNumber: 5
lockDuration: 10

database:
  url: 0.0.0.0
  port: 27017
  username: user
  password: pass
  db: test

broker:
  url: 0.0.0.0
  port: 6379
  username: user
  password: pass
  db: 0
